# Generated by Django 4.2.1 on 2023-05-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_doctor_specialty_delete_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
