# Generated by Django 4.2.1 on 2023-05-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_alter_user_date_of_birth'),
        ('base', '0003_doctor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.clinic'),
        ),
    ]
