# Generated by Django 4.2.1 on 2023-05-06 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_appointment_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointment_cr_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointment_up_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
