# Generated by Django 4.2.1 on 2023-05-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_availabilitiy_cr_by_alter_availabilitiy_up_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitiy',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.doctor'),
        ),
    ]
